### ISSUE TITLE
Failure due to `Unavailable QM Choice: CM1L - Aborted`.

### ISSUE THREAD

**Issue by shishaochen** [Isra3l/ligpargen#11]
Thanks for your great job on this pretty tool!

Sadly, I am blocked in generating force field files for a molecule using `CM1A-LBCC` charge model.
The command to reproduce error is:
```bash
ligpargen -s 'O=C(NC1CCCCC1)[C@H](C1CCCCC1)n1c2ccccc2nc1c1ccc(OC)cc1OC' -n FXR_6 -r UNK -p tmp
```

The failure comes from BOSS with error recorded in file `tmp/out`:
```text
Unavailable QM Choice: CM1L - Aborted
```

However, if I uploaded the molecule to LigParGen web server, no error happened and force field files were generated.
Could you please help debug & fix it?

Thanks a lot!

**Comment by Isra3l** [comment]
Hey! Probably you are using BOSS4.9 (default version). You should send an email to prof. Jorgensen to request BOSS5.0 because you want to use this ligpargen version. Other people have experienced the same issue and BOSS5.0 fixed it.

I hope it works,

Israel
