### ISSUE TITLE
Net charge is not zero due to rounding

### ISSUE THREAD

**Issue by BJWiley233** [Isra3l/ligpargen#14]
Hi,

This error is actually discovered in either GROMACs or probably as well in APBS because for neutral molecules ligpargen will actually have slightly positive or negative charges in the *gmx.itp and *.pqr files due to rounding, i.e. total net charge for molecule is + or - (0.0001 to 0.0005).  Is  there a way we can correct this in ligpargen?

See:
https://gromacs.bioexcel.eu/t/ligpargen-parameterized-ligand-for-opls-aa-m-introduces-a-non-integer-charger/428/5
https://gromacs.bioexcel.eu/t/total-charge-error-in-itp-files/486
https://gromacs.bioexcel.eu/t/ligpargen-toluene-itp-file/4023

**Comment by Isra3l** [comment]
Hey BJ,

You could change it manually just by removing/adding the charge difference to one atom of your molecule. As we are talking about tiny charge difference values it should not affect the simulation. When I will have time, I will fix it. 

Thank you for your feedback, I appreciate it.

Israel

**Comment by BJWiley233** [comment]
Yes @Isra3l, tiny differences so manually adjusting as we go 😄.
