### ISSUE TITLE
Which local version of ligpargen does the website version correspond to

### ISSUE THREAD

**Issue by Lumen97** [Isra3l/ligpargen#17]

**Comment by Lumen97** [comment]
I encountered compatibility problems when using feprepare 
https://feprepare.vi-seem.eu/

**Comment by Isra3l** [comment]
Hey Lumen97,

Fepprepare is created and maintained by the Cournia lab. They obtained a version of LigParGen used in the server from Leela's GitHub repository. As far as I know, they implemented the FEP part from scratch and use LigParGen only to generate the initial parameters of each molecule.
