### ISSUE TITLE
input file: does not exit

### ISSUE THREAD

**Issue by GDUTchenzikang** [Isra3l/ligpargen#19]
As the title,though all my input files are in the same folder and the ligpargen can be used,it still run out with **input file: does not exit**

Here is my command
> ligpargen -i TSFI.pdb -n TFSI -P TFSI -r MOL -c -1 -0 0 -cgen CM1A

**Comment by marcodigennaro** [comment]
can you show the output as well?

**Comment by Isra3l** [comment]
Hey,

I'm not sure what the issue could be. Could you please check if the file is in the same folder? I have not been able to reproduce the error, and no one else has reported this issue.
