### ISSUE TITLE
Dihedral angles of linear groups on 5-membered rings

### ISSUE THREAD

**Issue by ivokabelka** [Isra3l/ligpargen#20]
Compounds with a linear group (N≡C– or HC≡C–) attached to a 5-membered ring cause simulations to crash (tested with Gromacs). Before the crash, the rings become distorted. Compounds with a 6-membered ring are unaffected. By comparing the parameters generated for compounds with 5- and 6-membered rings, the issue seems to be with the coefficients of proper dihedrals that terminate with the nitrogen or carbon. In the case of 5-membered rings, the coefficients are non-zero. In some compounds, the torsion angle that terminates in the N≡**C**– carbon also has different coefficients than those in compounds with 6-membered rings. Making modifications to these parameters seems to fix the issue. The problem can be reproduced with the following compounds:

Mol_01: o1cc(C#**C**)cc1
[ dihedrals ]
; PROPER DIHEDRAL ANGLES
;  ai    aj    ak    al funct c0 c1 c2 c3 c4 c5
    7    6    3    4        3       9.079   0.000  -9.079  -0.000  -0.000   0.000
    6    3    4    **5**        3       9.079   0.000  -9.079  -0.000  -0.000   0.000

Mol_02: o1cc(C#**N**)cc1
    7    6    3    4        3       9.079   0.000  -9.079  -0.000  -0.000   0.000
    6    3    4    **5**        3       9.079   0.000  -9.079  -0.000  -0.000   0.000

Mol_03: o1c2ccccc2c(C#**N**)c1
   11    8    9   **10**        3      30.334   0.000  -30.334  -0.000  -0.000   0.000

Mol_04: o1cccc1C#**C**c2ccccc2
    **7**    6    5    1        3       9.079   0.000  -9.079  -0.000  -0.000   0.000

![cmpds](https://github.com/Isra3l/ligpargen/assets/34597684/6caa1ce1-136d-49a9-9a3a-ab69d292bef1)

**Comment by Isra3l** [comment]
1-4 term for GROMACS was fixed. So, it should work now.
