### ISSUE TITLE
Incorrect import of `pybel`

### ISSUE THREAD

**Issue by iGulitch** [Isra3l/ligpargen#26]
[Here](https://github.com/Isra3l/ligpargen/blob/0ce10107d1ccf3dce1d8a5b7fabd8dfc12fdeebe/ligpargen/tools/utilities.py#L135), the package **pybel** is imported incorrectly as `import pybel`. This leads to errors for big molecules created out of SMILES, since **AllChem.EmbedMolecule** of **RDKit** struggles to guess the atom coordinates of a molecule.

Namely, the following set of commands :
```
APP="ligpargen"
MOL="NAME"
SMILES='C/C=C(\CC/C=C(\CC/C=C(\CC/C=C(\CC/C=C(/CC/C=C(\C)CCC=C(C)C)CC/C=C(\C)CC/C=C(\C)CCC=C(C)C)CC/C=C(\C)CCC=C(C)C)CC/C=C(\C)CCC=C(C)C)CC/C=C(\C)CCC=C(C)C)CC/C=C(\C)CCC=C(C)C'
ligpargen -s '${SMILES}' -n ${MOL} -p ${MOL} -r MOL -c 0 -o 0 -cgen CM1A
```
leads to the following error :
```Traceback (most recent call last):
  File "/opt/conda/envs/ligpargen/bin/ligpargen", line 33, in <module>
    sys.exit(load_entry_point('LigPargen', 'console_scripts', 'ligpargen')())
  File "/ligpargen/ligpargen/ligpargen.py", line 504, in main
    molname=args.molname, workdir= args.path, debug= args.debug)
  File "<string>", line 17, in __init__
  File "/ligpargen/ligpargen/ligpargen.py", line 174, in __post_init__
    moleculeRDkit, newIndexToOriginalIndex, atomsNameOriginal, residueNameOriginal = utilities.generateRDkitMolecule(self.ifile, self.smile, self.workdir, molnameA, self.debug)
  File "/ligpargen/ligpargen/tools/utilities.py", line 139, in generateRDkitMolecule
    mymol = pybel.readstring('smi', smile)
AttributeError: module 'pybel' has no attribute 'readstring'
```
Importing **pybel** as `from openbabel import pybel` solves the issue. I have tried it separately with **RDKit** in the Linux prompt and succeeded.

Would you fix the **pybel** import, please? I suppose, `import openbabel` might be necessary as well, but I'm not 100% sure.

**Comment by Isra3l** [comment]
Dear iGulitch,

I have resolved the issue by following your suggestion. Thank you for your valuable feedback.

Best,

Israel
