### ISSUE TITLE
BOSS in 32 bit

### ISSUE THREAD

**Issue by punkpony** [Isra3l/ligpargen#3]
There are a lot of issues with using ligpargen, as I understand it is related to BOSS coming as a 32 bit compiled code. 
i.e. it will NOT run on a Mac (thanks for the recent 64 bit upgrade!) or any Linux that is 64 bit.

PS - to check what is your machine use `uname -a` 

if you run BOSS directy, you will see errors like:
```
./boss/autozmat -x -i boss -o pdb -p tmppar
./boss/autozmat: Exec format error. Binary file not executable.
```

if you run ligpargen, you will get misguiding errors like:
`FileNotFoundError: [Errno 2] No such file or directory: 'plt.pdb'`
or
`ERROR!    Open Babel is not installed on your work station.`

as mentioned in issue #1 

I guess it all just boils to getting BOSS for 64 bit.

@Isra3l also tagging @leelasd as another ligpargen guru :) 
**Is it possible to get BOSS as 64 bit or non-compiled? **  

Thank you!

**Comment by Isra3l** [comment]
Hey Valentina!

I have just fixed the open babel NOT installed error. 

Sadly, BOSS source code and BOSS64 are not available but you can run any 32 bits program like BOSS in a 64 bits Linux by installing a few libraries. I am not sure if it is possible for Windows(WSL) or Mac.  

For ubuntu check this link --->    https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit

I have been using many different Linux 64 bits distributions and I never had any problem with 32 bits executables. 

My machine ---> 

  Operating System: Ubuntu 20.04.2 LTS
  Kernel: Linux 5.4.0-96-generic
  Architecture: x86-64

The missing 'plt.pdb' file is an error related to BOSS. Adding these missing 32 bits libraries you should be able to run BOSS and fix this issue. 

I hope it helps,

Israel
