### ISSUE TITLE
Weird atom typing by LigParGen? 

### ISSUE THREAD

**Issue by iGulitch** [Isra3l/ligpargen#33]
Hello!

I'm attempting to atomtype [HMMM molecule](https://pubchem.ncbi.nlm.nih.gov/compound/Hexa_methoxymethyl_melamine).

LigParGen [locally installed] claims that those _nitrogens_ bonded to the ring _carbons_ have the atom type **N**. I have serious doubts about it, since, according to the [OPLS/2020 Force Field atom type list](https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.3c06602/suppl_file/jp3c06602_si_001.pdf) , **N** is the atom type of _amide nitrogens_, and the prerequisite for _amide_ is the double-bonded pair C=O linked to a _nitrogen_. In HMMM, there is no doubled bonded pair C=O and thus there should be no _amides_ identified.

Incorrect identification of the aforementioned _nitrogens_ leads in turn to the incorrect atom-typing of _carbons_ bonded to _nitrogens_ from the side of _oxygens_. These 6 _carbons_ are claimed to have the type **CT**, i.e. _alkane carbons_. IMHO, this is correct. There are ~216 **CT** atoms in the [OPLS/2020 Force Field supplementary material](https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.3c06602/suppl_file/jp3c06602_si_002.txt) , and ~11 of them are related to _amides_. I guess those 6 _carbons_ are recognised as the _amide_ ones that might be wrong.

The discussion above leads to a more general question about the mechanism of atom type identification that is implemented in **LigParGen**. For instance, [foyer](https://github.com/mosdef-hub/foyer/) does atom typing based on the SMARTS sequences. What does **LigParGen** use?

**Comment by jewettaij** [comment]
This might be related to #34

**Comment by iGulitch** [comment]
> #34 also seems like it might be an issue with atom typing.

Looked into #34. Crap, if LPG fails for a trivial ethylene, then I'm not surprised about HMMM result. Yet, I'm curious about the atom typing mechanism, because at least LPG works!

May I ask what the other molecules are, for which you tried LPG? I saw you mentioned benzoic acid. Anything else?

**Comment by jewettaij** [comment]
Alas, no.  I have only tested ethylene and benzoic acid.  *(The benzoic acid files created by ligpargen seemed okay, ...but I was only looking at the improper interactions.  I was actually only using LigParGen to verify that the impropers generated by moltemplate were correct.  But it's difficult to tell, since I'm not sure I completely trust LigParGen.)*

**Comment by jewettaij** [comment]
> "because somehow LPG still works for basically any molecule [ not significantly big ] that I've tried so far!"

I'm glad to hear that!

**Comment by iGulitch** [comment]
> On that note, I don't know how to get LigParGen to reveal the original OPLS atom type that it's using. I would really like that. Instead, LigParGen returns atom types with names like "C801", which isn't very informative.

AFAIU, "**C801**" isn't "_atom type_" [**C, CT, CM, NT, CA, ...** ] , but "_atom class_" [**opls_801**, ...] . See the [supplementary 1](https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.3c06602/suppl_file/jp3c06602_si_001.pdf) of the latest [OPLS paper](https://pubs.acs.org/doi/10.1021/acs.jpcb.3c06602).

Nonetheless, I understand you 100%. If you take a look in the [supplementary 2](https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.3c06602/suppl_file/jp3c06602_si_002.txt) of the latest [OPLS paper](https://pubs.acs.org/doi/10.1021/acs.jpcb.3c06602), then you find there the following :
```
800                                        800-899 reserved for QM/MM atoms - do not use - they
899                                        will be read from the Z-matrix file, not from here
 ```
LPG seems to perform QuantChem in the background always and has atom classes **opls_800-899** reserved for those atoms, because I see only these atom classes **opls_800-899**. I also checked some polymer molecules, and figured out that when **800-899** isn't enough, then LPG bollows atom classes from "**opls_9500**" and onwards. At the same time, AFAIU, atom typing shouldn't be dependent on whether QuantChem is performed or not, should it? I asked LPG developers about atom typing mechanism, but they are silent. Looks like, source code digging is the only way to figure it out.

**Comment by iGulitch** [comment]
> > "because somehow LPG still works for basically any molecule [ not significantly big ] that I've tried so far!"
> 
> I'm relieved to hear that!

Let me clarify, not for `literally every molecule`, but for vast majority of them. However, apparently, a careful check now is mandatory for each and every molecules parametrised using LPG.

LPG seems to fail in two cases :
1. too big molecule. then, QuantChem simulations performed in the background impose limitations on the molecule size. see the dicsussion [here](https://github.com/Isra3l/ligpargen/issues/27)
2. too complicated SMILES sequence. Since LPG uses RDKit to reconstruct a molecule from scratch, it depends on whether the default RDKit routine succeeds. Firstly, the way how LPG tries to reconstruct a molecule by default fails quite easy :
```
molecule = Chem.MolFromSmiles(smile)
molecule = Chem.AddHs(molecule)
done = AllChem.EmbedMolecule(molecule, randomSeed=0xf00d)
```
Secondly, [LPG incorrectly imports pybel](https://github.com/Isra3l/ligpargen/issues/26).

Here is my experience with it. I hope it's useful for you.

**Comment by jewettaij** [comment]
> Here is my experience with it. I hope it's useful for you.

It is.  Thanks!  And thanks for explaining those atom types.

> However, apparently, a careful check now is mandatory for each and every molecules parametrised using LPG.

I would recommend it for most open-source science software, especially if it depends on other files, force-fields, or APIS which are changing often.

The grad students and postdocs who worked on progams like LigParGen move on.  In some cases, code barely works well enough to get the paper out, and then people move on.  They have to.  Those are the incentives in academia.

*(I myself wrote such a program which is moderately popular.  I supported it actively for a few years.  But when I had a full-time 70+ hrs/week job in a completely unrelated field, I had to deprioritize it.  2 years later, during a work gap, I started updating again, and it took almost 2 weeks of focus to patch most of the remaining unresolved issues.  There's no way I could do that normally.)*

> Looks like, source code digging is the only way to figure it out.

I took a glance at it a couple years ago.  I wish you luck.

**Comment by iGulitch** [comment]
@jewettaij , I wouldn't count on your last statement if I were you. Unfortunately, Israel doesn't reply often, but I'd rather say he does it randomly and occasionally :( I was already just about calling him directly to Upsala University in Sweden by phone :D

**Comment by iGulitch** [comment]
> LigParGen has some BOSS dependencies, so this might make the code tricky to read.
Any of them is responsible for the atom typing, do you know? I thought BOSS was only for the QM calculations to evaluate atom charges, whereas the atom typing itself was solely made by LigParGen. This is why I was trying to read through the source code of LigParGen.

**Comment by Isra3l** [comment]
Hey Everyone,

I just replied to Issue #34, and the same answer applies here. Briefly, BOSS is responsible for atom type determination, so for issues related to atom types, please contact Bill Jorgensen directly. You can find instructions on how to check the original OPLS atom type assignment in my #34 reply.

Additionally, I would modify the statement to: "A careful check IS ALWAYS mandatory for each and every molecule parameterized using ANY SOFTWARE." This applies regardless of whether the code is maintained by a professor, a staff scientist, or a company. 

Best,

Israel
