### ISSUE TITLE
improper interactions for ethylene disagree with .par file from 2023 paper

### ISSUE THREAD

**Issue by jewettaij** [Isra3l/ligpargen#34]
Thanks for creating/maintaining ligpargen.  It is very useful.

I noticed a problem in the strength of the improper interaction for a simple molecule (ethylene) that was generated by ligpargen today. 
![ethylene-3d](https://github.com/user-attachments/assets/a398d94d-d15b-4050-9b6e-b35be3b63cb7)

Here is an excerpt from the [UNK_54BCB3.prm](https://github.com/user-attachments/files/18011149/UNK_54BCB3.prm.txt) file for that molecule (CHARM/.prm format):
```
IMPROPER 
H803 C800 C801 H802 2.50000 2 180.00000 
H805 C801 C800 H804 2.50000 2 180.00000 
```
The coefficient (2.50000) is too weak.  I think it should be 15.00000.
It seems like perhaps ligpargen is assigning the carbon to the wrong atom type.

Here's why I think that:

# Table of improper parameters from the 2023 paper
*For reference, here's the full list of improper interactions from the* [supplemental section of the 2023 paper](https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.3c06602/suppl_file/jp3c06602_si_002.txt), (in BOSS/.par format):
```
160   0.0      21.0       0.0       0.0        O -C -X -Y      improper torsion                     
161   0.0       5.0       0.0       0.0        Z -N -X -Y      improper torsion 9/08 was 2.0        
162   0.0       5.0       0.0       0.0        Z -CA-X -Y      improper torsion 9/08 was 2.2  
221   0.0      30.0       0.0       0.0        Z -CM-X -Y      improper torsion 
277   0.0      -8.0       0.0       0.0        CM-HC-CM-HC     allenes improper
277   0.0      -8.0       0.0       0.0        CM-HC-CM-CT     allenes improper                     
277   0.0      -8.0       0.0       0.0        CM-CT-CM-HC     allenes improper                     
277   0.0      -8.0       0.0       0.0        CM-CT-CM-CT     allenes improper  
```

Ethylene molecules should be using `Z -CM-X -Y` because the carbon for ethylene is "CM"
```
143 06 CM   -0.230     3.550     0.076     alkene C (H2-C=) all atom
```
But it looks like ligpargen is using `Z -CA-X -Y` instead (treating this carbon atom as type "CA") because the improper coefficient generated by ligpargen is 2.5 not 15.0.  *(Note that there's a factor of 2 difference between the impropers/dihedrals because of the different conventions used by CHARMM and BOSS.)*

## Other impropers from ligpargen appear to be correct
For comparison, I also tried using ligpargen to generate files for a different molecule (benzoic acid, `O=C(O)c1ccccc1`), and the resulting impropers were correct. *([UNK_CF29F3.prm](https://github.com/user-attachments/files/18011335/UNK_CF29F3.prm.txt))*

In my limited tests, I've only had problems with ethylene so far.

**Comment by Isra3l** [comment]
Dear Andrew,

LigParGen uses BOSS to determine atom types, and BOSS is a closed-source software. If there are any issues regarding parameterization, I would strongly suggest you contact Bill Jorgensen directly. You could include a link to this GitHub issue to help him better understand the problem.

You can also check the OPLS atom type assigned by examining the BOSS Z-matrix file generated (.z). This file uses the original atom types from the manuscript before converting them to others like opls_800. At the end of the file, you will find rows such as:

800  6 CR  -0.094116  3.550000  0.070000

Here, CR represents the assigned OPLS atom type.

I hope this helps!

Best,

Israel

**Comment by jewettaij** [comment]
## Summary: The atom typing *was correct* for this example.

LigParGen seems to be looking up the wrong improper parameters for some other reason.

> You can also check the OPLS atom type assigned by examining the BOSS Z-matrix file generated (.z). This file uses the original atom types from the manuscript before converting them to others like opls_800. At the end of the file, you will find rows such as:
> 
> 800 6 CR -0.094116 3.550000 0.070000
> Here, CR represents the assigned OPLS atom type.
> I hope this helps!

Oh wow.  Yes it does!

## Followup request: Document this feature?

*Incidentally, people have been asking this feature for a while (including me), to no avail.  (Example [here](https://github.com/leelasd/ligpargen/issues/46).)  Lots of people don't realize LigParGen already reveals these atom types in the .z matrix file.  Perhaps you can mention this somewhere in the documentation?  Knowing the atom type is a really useful way to double-check LigParGen output.*

--------------------------
## ...back to this example

So, for the z-matrix file I received from the LigParGen website *([UNK_9DE0DF.z.txt](https://github.com/user-attachments/files/18133840/UNK_9DE0DF.z.txt))*, the carbon atoms were apparently assigned to the "CM" atom type, which is correct.  (Yay!)  Excerpt:
```
 800  6 CM  -0.250555  3.550000  0.076000  
```
...So I guess this is not an issue with atom typing.

I wonder why LigParGen thinks the improper interaction strength for ethylene is so weak?

**Comment by Isra3l** [comment]
Hey Andrew,

I forgot to mention that BOSS assigns the atom types and the corresponding
parameter values based on those assignments. LigParGen is essentially a
wrapper that reads these parameters and converts them into the appropriate
format for various software. I recommend using the debug flag in LigParGen
because it will output intermediate BOSS files, where you can review the
assigned forcefield parameters, including the types and values.

Here’s an example from an output file:

 Dihedral                             Fourier Coefficients
   Angle    Atom  I Type F    V1        V2        V3        V4
  Phases          Delta
      1      * 7*  165  165     0.000     7.250     0.000     0.000
 0.00   0.00   0.00     2.0      All Solutes
      2       8  165  165     0.000     7.250     0.000     0.000      0.00
  0.00   0.00     2.0      All Solutes
      3       9  165  165     0.000     7.250     0.000     0.000      0.00
  0.00   0.00     2.0      All Solutes

In this case, Atom 7 refers to the dihedral defined in the Z-matrix by atom
7 (" *7 *   C03       803     803    *6 *    1.3795    *4 *  122.8050    *5
*    0.0127"   so the dihedral *7-6-4-5*)

I hope this helps!

Best,

Israel

**Comment by jewettaij** [comment]
Hi Israel.  Yes this is helpful.

After looking at your example I realized that the z-matrix file returned by the LigParGen server ([UNK_9DE0DF.z](https://github.com/user-attachments/files/18133840/UNK_9DE0DF.z.txt) shows an inconsistency.
The dihedrals section of that file:
```
                    Variable Dihedrals follow     (3I4,F12.6)                   
   6 162 162    2.000000
   7 222 222    2.000000
   8 162 162    2.000000
```
...indicates that a dihedral interaction of type `162` is being used.  That interaction is defined [here in the original PAR file](https://github.com/jewettaij/moltemplate/blob/728ee239ed21d640abed7a25451eb4e1a3fc661e/moltemplate/force_fields/oplsaa2023_original_format/Jorgensen_et_al-2023-The_Journal_of_Physical_Chemistry_B.sup-2.par#L1481).
*Excerpt:*
```
162   0.0       5.0       0.0       0.0        Z -CA-X -Y      improper torsion 9/08 was 2.2  
```
- From the `Z -CA-X -Y`, it looks like the dihedrals (impropers) are being assigned for an atom of type "CA".
- However, earlier in that file, it says that the carbon atoms are of type "CM":
```
 800  6 CM  -0.250555  3.550000  0.076000                                       
 801  6 CM  -0.250555  3.550000  0.076000 
```
This looks like it might be a bug.
I will send professor Jorgensen an email.

Thanks for all the help!

**Comment by jewettaij** [comment]
Professor Jorgensen replied.  He said:
" The way the Z-matrix is written, dihedrals # 6 and 8 are improper dihedrals, so the program assigns the generic improper type 162. The other four are proper HC-CM-CM-HC dihedrals and are given type 222.This  Z-matrix should give a good planar/perpendicular energy barrier. So, not a bug. WJ"
