### ISSUE TITLE
document where to find atom types and force-field interaction types in Z-matrix files

### ISSUE THREAD

**Issue by jewettaij** [Isra3l/ligpargen#35]
Thanks for your help on #34

*No good deed goes unpunished...*

Here's a feature request:

## request 1

Can we add a section to the documentation which explains how to troubleshoot atom typing and force-field typing issues using the Z-matrix file returned by LigParGen.  *(If you want to discuss other BOSS output files or how to run LigParGen in debug mode, that's fine too.)*

Why:  It seems like some of the issues that people have historically blamed on LigParGen are actually BOSS issues.  *(For example: [this issue](https://github.com/leelasd/ligpargen/issues/92) from the [previous LPG repository](https://github.com/leelasd/ligpargen/issues))*.

The information you've shared with me (while discussing issue #34) has been so helpful.  It would be a pity if nobody else reads that conversation.  That's why a quick troubleshooting guide might be helpful. 

***Alternatively, if it's too much trouble write a troubleshooting guide, then perhaps you can post include a [link to that issue #34](https://github.com/Isra3l/ligpargen/issues/34#issuecomment-2539951531) somewhere in the docs where people who are struggling might see it.***

---------------------------
To clarify what I mean, here's an excerpt from that conversation which could go in a troubleshooting guide:
 
Example of atom type information from the .z file:
```
 Final Non-Bonded Parameters for QM (AM1 CM1Ax1.14) Atoms:                      
 800  6 CM  -0.250555  3.550000  0.076000                                                                     
 801  6 CM  -0.250555  3.550000  0.076000                                       
 802  1 HC   0.125278  2.500000  0.030000                                       
 803  1 HC   0.125278  2.500000  0.030000 
  :
```
Example of force-field interaction types:
```
                    Variable Dihedrals follow     (3I4,F12.6)                   
   6 162 162    2.000000
   7 222 222    2.000000
   8 162 162    2.000000
   :
```
Also mention where users can lookup these interaction types ("162", "222") in the [original boss file](https://pubs.acs.org/doi/suppl/10.1021/acs.jpcb.3c06602/suppl_file/jp3c06602_si_002.txt).  Excerpt:
```
162   0.0       5.0       0.0       0.0        Z -CA-X -Y      improper torsion 9/08 was 2.2  
```

## request 2

So that people notice the guide, please post link to this troubleshooting guide on the LigParGen server website as well.

## request 3
That [website](https://zarbi.chem.yale.edu/ligpargen/) needs to be updated anyway.  It directs people to report issues to the [wrong github repository](https://github.com/leelasd/ligpargen/issues).

**Comment by Isra3l** [comment]
Dear Andrew,

Thank you for your feedback. I have added a new section in the README based on your suggestions (Request 1). Unfortunately, I cannot help with the other two requests related to the web server, as I need explicit permission from Bill Jorgensen to make such changes. Additionally, updating the server code would be complex. The server still runs on the original published code (version 1), and I do not anticipate it being updated in the near future.

Best,

Israel

**Comment by jewettaij** [comment]
Awesome!  That's great!  It helps because many of us are unfamiliar with .z (z-matrix) files (or BOSS).

It's too bad the server is not running your version of LigParGen.  You have demonstrated commitment to maintaining this software and responding to users, which (I think) justifies switching versions.
Thanks for maintaining a great service.
