### ISSUE TITLE
Error when processing CM1A-LBCC charges

### ISSUE THREAD

**Issue by wutobias** [Isra3l/ligpargen#4]
[env.yaml.zip](https://github.com/Isra3l/ligpargen/files/8100170/env.yaml.zip)
When running the following command:

`ligpargen -s 'c1ccc(cc1)O' -n phenol -cgen CM1A-LBCC`

I am getting the following error message:

```
Traceback (most recent call last):
  File "/home/tobias/progs/anaconda3/envs/xtalmd/bin/ligpargen", line 33, in <module>
    sys.exit(load_entry_point('LigPargen', 'console_scripts', 'ligpargen')())
  File "/data/tobias_data/progs/ligpargen/ligpargen/ligpargen.py", line 496, in main
    molname=args.molname, workdir= args.path, debug= args.debug)
  File "<string>", line 17, in __init__
  File "/data/tobias_data/progs/ligpargen/ligpargen/ligpargen.py", line 192, in __post_init__
    moleculeA = Molecule.fromBOSS(zmatName, outFile, pdbFile, moleculeA.shiftX, moleculeA.shiftY, moleculeA.shiftZ)
  File "/data/tobias_data/progs/ligpargen/ligpargen/topology/Molecule.py", line 141, in fromBOSS
    atoms, numberOfStructuralDummyAtoms = cls._getAtoms(cls, zmatData, pdbfile)
  File "/data/tobias_data/progs/ligpargen/ligpargen/topology/Molecule.py", line 460, in _getAtoms
    atomsLines = re.search(r'BOSS(.*?)Geometry', zmatData, re.DOTALL).group().splitlines()[1:-1]
AttributeError: 'NoneType' object has no attribute 'group'
```

The temporary out file in the working directory contains 

```
Unavailable QM Choice: CM1L - Aborted
```

This might be a bug related to how the input is parsed to BOSS. Any help is greatly appreciated. For reference, running `ligpargen -s 'c1ccc(cc1)O' -n phenol -cgen CM1A` works just fine.

Attaching yaml file from my conda environment.

--Tobias

**Comment by Isra3l** [comment]
Hey Tobias! 

Thanks for your help! I have just merged your XML changes. CM1A-LBCC charge model requires BOSS5.0 but the BOSS version provided by the official website is BOSS4.9. I would recommend you to send an email directly to Prof. W. L. Jorgensen requesting BOSS5.0 because I am not sure when he is planning to update the official version.

Best,

Israel
