### ISSUE TITLE
A error happened when running ligpargen

### ISSUE THREAD

**Issue by TerryHangLyu** [Isra3l/ligpargen#8]
Dear developer,

 I installed ligpargen as suggested in the README.md. And when I ran the test, it seemed ok. But when I typed the command "ligpargen -s 'c1ccc(cc1)O'" in the terminal, a error happened, which said the file 'plt.pdb' doesn't exist. Now, the error also shows up even when I do not use the smiles string as input. I am writing to ask for help to get ligpargen installed correctly. Can you give me some advice to deal with it? 

Best wishes,
Hang LYU

PS:
Test
![image](https://user-images.githubusercontent.com/55949849/169368795-fbb6aa2c-ff85-4253-96e4-972693e92099.png)
The error
![image](https://user-images.githubusercontent.com/55949849/169368108-3a903378-904b-4256-a9df-3a8b1050ee09.png)

**Comment by Isra3l** [comment]
Dear Hang,

Did you fix the error installing BOSS properly as I suggested to you in the email? (Probably 32 bits libraries missing)

Best,

Israel

**Comment by TerryHangLyu** [comment]
Dear Israel,
   Sorry for the late reply. Maybe something went wrong about my email, but I didn't receive the mail about the installation of BOSS from you. My email address is hlyuai@connect.ust.hk. Could you please resend to me the mail about installing BOSS? So sorry for bothering you again.

Best,
Hang

**Comment by Isra3l** [comment]
Dear Hang,

Have you tried the charge model CM1A?  My version works fine and I suspect that the problem is your BOSS version. Probably you are using BOSS4.9 but you should use BOSS5.0 for the CM1A-LBCC charge model. Try:

ligpargen -s 'c1ccc(cc1)O -cgen CM1A  -p mymol

If you have any errors, I would suggest you send an email to Bill Jorgensen and ask him to get the BOSS5.0 version. Just, tell him that you are interested in using the Ligpargen command-line version with CM1A-LBCC from my Github and you need BOSS5.0.

I hope it works,

Best,

Israel

**Comment by TerryHangLyu** [comment]
> Dear Hang,
> 
> Have you tried the charge model CM1A? My version works fine and I suspect that the problem is your BOSS version. Probably you are using BOSS4.9 but you should use BOSS5.0 for the CM1A-LBCC charge model. Try:
> 
> ligpargen -s 'c1ccc(cc1)O -cgen CM1A -p mymol
> 
> If you have any errors, I would suggest you send an email to Bill Jorgensen and ask him to get the BOSS5.0 version. Just, tell him that you are interested in using the Ligpargen command-line version with CM1A-LBCC from my Github and you need BOSS5.0.
> 
> I hope it works,
> 
> Best,
> 
> Israel

Thanks so much for your suggestions. Will try it later

**Comment by TerryHangLyu** [comment]
> 
Dear Israel,

   Thanks for your help. I have contacted the developer of BOSS5.0 for the link to download it. After installing BOSS5.0, Ligpargen can work well in my computer now.

Best wishes and thanks,
Hang LYU
