### ISSUE TITLE
Discrepancies between LigParGen server and ligpargen 2.1 in xyz/key files

### ISSUE THREAD

**Issue by eneas77** [Isra3l/ligpargen#9]
Hi,

When submitting and contrasting the two results of parametrization of the same molecule and geometry with server version against command-line one, discrepancies appear in the tandem tinker type files:
[lig.txt](https://github.com/Isra3l/ligpargen/files/8760699/lig.txt)
[lig.comline.xyz.txt](https://github.com/Isra3l/ligpargen/files/8760718/lig.comline.xyz.txt)
[lig_server.key.txt](https://github.com/Isra3l/ligpargen/files/8760720/lig_server.key.txt)
[lig_server.xyz.txt](https://github.com/Isra3l/ligpargen/files/8760721/lig_server.xyz.txt)
[lig.comline.key.txt](https://github.com/Isra3l/ligpargen/files/8760722/lig.comline.key.txt)

Server options: upload pdb file + CM1A option + 0 optimizations + charge (+1)
ComLine options: ligpargen -i lig.pdb -cgen CM1A -r MOL -c 1 -o 0

There are discrepancies in both xyz and jey files when comparing. Moreover, tinker analyze routine works fine for server outputs but not for comline ones, returning a error of connectivity between first atoms.

Any hints about this? Not checked otehr ligpargen 2.1 outputs as i require tinker ones.

HOpe this helps...

Thank you,

E77

**Comment by Isra3l** [comment]
Dear E77,

Thank you for your help finding bugs. I have fixed a problem in the tinker XYZ format output produced by the introduction of new features. Now, it should work. Please, take a look and let me know if you find any other problems.

Best,

Israel
